name: Build and Deploy Java Application into Tomcat Server on EC2

on:
  push:
    branches: [ "production" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install -f SampleWebApp/pom.xml

    - name: Run Unit Tests
      run: mvn test -f SampleWebApp/pom.xml

    - name: Upload WAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SampleWebApp-war
        path: SampleWebApp/target/SampleWebApp.war

    - name: Deploy to Tomcat
      run: |
        echo "Deploying a WAR file to Tomcat on EC2 instance..."
        curl -v -u "${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}" \
        -T SampleWebApp/target/SampleWebApp.war \
        "http://${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/SampleWebApp&update=true"